{% set name = "starsessions" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starsessions-{{ version }}.tar.gz
  sha256: ce5e4448d9bf2c76222e56cd099ad92d22313e8a4def612e22b71a122cc11da0

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv

requirements:
  host:
    - pip
    - poetry-core
    - python
  run:
    - itsdangerous >=2.0.0,<3.0.0
    - python
    - starlette
  run_constrained:
    - redis-py >=4.2.0rc1

test:
  imports:
    - starsessions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  description: Advanced sessions for Starlette and FastAPI frameworks
  dev_url: https://github.com/alex-oleshkevich/starsessions
  doc_url: https://github.com/alex-oleshkevich/starsessions/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
