{% set name = "starsessions" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alex-oleshkevich/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d2e9a58dd44d0ebef53da261b3370cf03db7d7a7887e340e9096f2c1f1d62be

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - starlette
    - itsdangerous >2.0.0,<3.0.0
    - python
    - starlette <1.0
  run_constrained:
    - redis >=4.2.0

# redis >=4.2.0 is not in the main channel
{% set ignore_tests = " --ignore=tests/backends/test_redis.py" %}
test:
  source_files:
    - tests
  imports:
    - starsessions
  commands:
    - pip check
    - pytest -v tests --asyncio-mode=auto {{ ignore_tests }}
  requires:
    - pip
    - pytest >=8,<9
    # relax pytest-asyncio upper bound
    - pytest-asyncio
    # relax lower bound for httpx
    - httpx >=0.27.0,<0.28

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  description: Advanced sessions for Starlette and FastAPI frameworks
  dev_url: https://github.com/alex-oleshkevich/starsessions
  doc_url: https://github.com/alex-oleshkevich/starsessions/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
