{% set name = "starsessions" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starsessions-{{ version }}.tar.gz
  sha256: 5c8d249712d4477155a7c549463780d6bb6516b91d49e25e39221158c9b79537

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6.2
  run:
    - aioredis >=2.0.0
    - itsdangerous >=2.0.1
    - python >=3.6.2
    - requests >=2.25.1
    - starlette

test:
  imports:
    - starsessions
    - starsessions.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-oleshkevich/starsessions
  summary: Pluggable session support for Starlette.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
